package:
  name: go
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install .[dev] -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.10.0

  run:
    - python


test:
  imports:
    - go
  source_files:
    - tests
  commands:
    - pytest

about:
  summary: a go library.
  license_file: LICENSE
